# CMake generated Testfile for 
# Source directory: /Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator
# Build directory: /Users/anupkaul/other_git/deepmind/build_mujoco/test/plugin/actuator
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(PidTest.PGain "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.PGain")
set_tests_properties(PidTest.PGain PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.PGainWithFilterExact "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.PGainWithFilterExact")
set_tests_properties(PidTest.PGainWithFilterExact PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.SlewMaxRate "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.SlewMaxRate")
set_tests_properties(PidTest.SlewMaxRate PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.IntegratedVelocitySlewMaxRate "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.IntegratedVelocitySlewMaxRate")
set_tests_properties(PidTest.IntegratedVelocitySlewMaxRate PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.SlewMaxRateUsesFirstCtrl "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.SlewMaxRateUsesFirstCtrl")
set_tests_properties(PidTest.SlewMaxRateUsesFirstCtrl PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.ITerm "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.ITerm")
set_tests_properties(PidTest.ITerm PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.FiniteDifferencing "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.FiniteDifferencing")
set_tests_properties(PidTest.FiniteDifferencing PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.CtrlClamp "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.CtrlClamp")
set_tests_properties(PidTest.CtrlClamp PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.CopyData "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.CopyData")
set_tests_properties(PidTest.CopyData PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.MultipleActuatorsSamePlugin "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.MultipleActuatorsSamePlugin")
set_tests_properties(PidTest.MultipleActuatorsSamePlugin PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.InvalidClamp "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.InvalidClamp")
set_tests_properties(PidTest.InvalidClamp PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
add_test(PidTest.InvalidSlew "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pid_test" "--gtest_filter=PidTest.InvalidSlew")
set_tests_properties(PidTest.InvalidSlew PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/actuator/CMakeLists.txt;0;")
