# CMake generated Testfile for 
# Source directory: /Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util
# Build directory: /Users/anupkaul/other_git/deepmind/build_mujoco/python/mujoco/util
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ArrayTraitsTest.CArrayType "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.CArrayType")
set_tests_properties(ArrayTraitsTest.CArrayType PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayNdim "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayNdim")
set_tests_properties(ArrayTraitsTest.ArrayNdim PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.ArrayScalarType "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.ArrayScalarType")
set_tests_properties(ArrayTraitsTest.ArrayScalarType PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(ArrayTraitsTest.MakeEigen "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/array_traits_test" "--gtest_filter=ArrayTraitsTest.MakeEigen")
set_tests_properties(ArrayTraitsTest.MakeEigen PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;69;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.IsCallable "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.IsCallable")
set_tests_properties(FuncTraitsTest.IsCallable PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgType "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgType")
set_tests_properties(FuncTraitsTest.FuncArgType PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncTraitsTest.FuncArgCount "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/func_traits_test" "--gtest_filter=FuncTraitsTest.FuncArgCount")
set_tests_properties(FuncTraitsTest.FuncArgCount PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;78;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.UnwrapArgs "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.UnwrapArgs")
set_tests_properties(FuncWrapTest.UnwrapArgs PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(FuncWrapTest.ReturnArrayArg0 "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/func_wrap_test" "--gtest_filter=FuncWrapTest.ReturnArrayArg0")
set_tests_properties(FuncWrapTest.ReturnArrayArg0 PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;87;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
add_test(TupleToolsTest.Slice "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/tuple_tools_test" "--gtest_filter=TupleToolsTest.Slice")
set_tests_properties(TupleToolsTest.Slice PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;96;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/python/mujoco/util/CMakeLists.txt;0;")
