# CMake generated Testfile for 
# Source directory: /Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity
# Build directory: /Users/anupkaul/other_git/deepmind/build_mujoco/test/plugin/elasticity
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ElasticityTest.FlexCompatibility "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.FlexCompatibility")
set_tests_properties(ElasticityTest.FlexCompatibility PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergyShell "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergyShell")
set_tests_properties(ElasticityTest.ElasticEnergyShell PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(PluginTest.ElasticEnergyMembrane "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=PluginTest.ElasticEnergyMembrane")
set_tests_properties(PluginTest.ElasticEnergyMembrane PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidThickness "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidThickness")
set_tests_properties(ElasticityTest.InvalidThickness PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ElasticEnergySolid "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.ElasticEnergySolid")
set_tests_properties(ElasticityTest.ElasticEnergySolid PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.CantileverIntoCircle "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.CantileverIntoCircle")
set_tests_properties(ElasticityTest.CantileverIntoCircle PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidTxtAttribute "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidTxtAttribute")
set_tests_properties(ElasticityTest.InvalidTxtAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.InvalidMixedAttribute "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.InvalidMixedAttribute")
set_tests_properties(ElasticityTest.InvalidMixedAttribute PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
add_test(ElasticityTest.ValidAttributes "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/elasticity_test" "--gtest_filter=ElasticityTest.ValidAttributes")
set_tests_properties(ElasticityTest.ValidAttributes PROPERTIES  ENVIRONMENT "MUJOCO_PLUGIN_DIR=/Users/anupkaul/other_git/deepmind/build_mujoco/lib" SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;15;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/plugin/elasticity/CMakeLists.txt;0;")
