# CMake generated Testfile for 
# Source directory: /Users/anupkaul/other_git/deepmind/mujoco/test
# Build directory: /Users/anupkaul/other_git/deepmind/build_mujoco/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(MujocoTestTest.MjUserWarningFailsTest "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/fixture_test" "--gtest_filter=MujocoTestTest.MjUserWarningFailsTest")
set_tests_properties(MujocoTestTest.MjUserWarningFailsTest PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;69;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(MujocoTestTest.MjUserErrorFailsTest "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/fixture_test" "--gtest_filter=MujocoTestTest.MjUserErrorFailsTest")
set_tests_properties(MujocoTestTest.MjUserErrorFailsTest PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;69;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(MujocoErrorTestGuardTest.NestedErrorGuards "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/fixture_test" "--gtest_filter=MujocoErrorTestGuardTest.NestedErrorGuards")
set_tests_properties(MujocoErrorTestGuardTest.NestedErrorGuards PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;69;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(MujocoTestTest.MockFilesystemTest "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/fixture_test" "--gtest_filter=MujocoTestTest.MockFilesystemTest")
set_tests_properties(MujocoTestTest.MockFilesystemTest PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;69;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(HeaderTest.IntsHave4Bytes "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/header_test" "--gtest_filter=HeaderTest.IntsHave4Bytes")
set_tests_properties(HeaderTest.IntsHave4Bytes PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;72;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(HeaderTest.IntsHaveAtLeast31Bits "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/header_test" "--gtest_filter=HeaderTest.IntsHaveAtLeast31Bits")
set_tests_properties(HeaderTest.IntsHaveAtLeast31Bits PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;72;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(HeaderTest.EnumsAreInts "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/header_test" "--gtest_filter=HeaderTest.EnumsAreInts")
set_tests_properties(HeaderTest.EnumsAreInts PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;72;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(PipelineTest.SparseDenseEquivalent "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pipeline_test" "--gtest_filter=PipelineTest.SparseDenseEquivalent")
set_tests_properties(PipelineTest.SparseDenseEquivalent PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;75;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
add_test(PipelineTest.DeterministicNoWarmstart "/Users/anupkaul/other_git/deepmind/build_mujoco/bin/pipeline_test" "--gtest_filter=PipelineTest.DeterministicNoWarmstart")
set_tests_properties(PipelineTest.DeterministicNoWarmstart PROPERTIES  SKIP_REGULAR_EXPRESSION "\\[  SKIPPED \\]" WORKING_DIRECTORY "/Users/anupkaul/other_git/deepmind/mujoco/test" _BACKTRACE_TRIPLES "/usr/local/Cellar/cmake/3.28.1/share/cmake/Modules/GoogleTest.cmake;402;add_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;37;gtest_add_tests;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;75;mujoco_test;/Users/anupkaul/other_git/deepmind/mujoco/test/CMakeLists.txt;0;")
subdirs("benchmark")
subdirs("engine")
subdirs("sample")
subdirs("user")
subdirs("xml")
subdirs("plugin/elasticity")
subdirs("plugin/actuator")
